name: Deploy Demo Site
on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Debug - List Directory Contents
        run: ls -al

      - name: Create CNAME for Demo
        run: echo "demo.gultbarn.no" > CNAME

      - name: Deploy to GitHub Pages (Demo)
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.DEMO_DEPLOY_TOKEN }}
          external_repository: TagFri/gultbarn-demo  # Replace with your actual demo repo "owner/repo"
          publish_dir: .
          publish_branch: gh-pages
          force_orphan: true
